{{- if .Values.postHook.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: post-hook
          image: "{{ .Values.postHook.image }}"
          command: {{ .Values.postHook.command }}
{{- end }}
